apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: components
  description: A collection of all Backstage example components
spec:
  targets:
    - ./components/artist1-lookup-component.yaml
